AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  NameBase:
    Description: This is the base name.
    Type: String
    Default: target-dynamic-ip
  
  MyKeyPair:
    Description: The EC2 Key Pair to allow SSH access to the instance
    Type: AWS::EC2::KeyPair::KeyName
        
Resources:
#--------------------------------------------------------#         
# EC2
#--------------------------------------------------------#
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      KeyName: !Ref MyKeyPair
      NetworkInterfaces: 
        - AssociatePublicIpAddress: "true"
          DeviceIndex: "0"
          SubnetId: !ImportValue "target-dynamic-ip-PublicSubnet01"
          GroupSet:
            - !Ref EC2SecurityGroupTarget       
      ImageId: ami-0d889f77081190db1
      IamInstanceProfile: !Ref InstanceProfile
      UserData:
        Fn::Base64: |
          #!/bin/bash
          sudo yum update -y
          sudo yum install git -y
      Tags:
        - Key: Name
          Value: !Sub ec2-${NameBase}
#--------------------------------------------------------#
# Security Group for EC2
#--------------------------------------------------------#
  EC2SecurityGroupTarget:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for EC2
      GroupName: !Sub ${NameBase}-ec2-sg
      VpcId: !ImportValue "target-dynamic-ip-vpc"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80  
          ToPort: 80
          SourceSecurityGroupId: !Ref ELBSecurityGroup     #ALB経由のHTTP通信のみ許可
          Description: HTTP Access Permission

        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
          Description: for circleci   #circleci無料プランだとIPアドレス範囲が分からないため全開放

      SecurityGroupEgress:
        - IpProtocol: "-1"
          CidrIp: 0.0.0.0/0        
      Tags:
        - Key: Name
          Value: !Sub ${NameBase}-ec2-sg

  ELBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for ELB(Elastic Load Balancer)
      GroupName: !Sub ${NameBase}-elb-sg
      VpcId: !ImportValue "target-dynamic-ip-vpc"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: !Sub ${NameBase}-elb-sg
#--------------------------------------------------------#         
# IAM Role
#--------------------------------------------------------#
  S3FullAccessRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: S3FullAccessRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal:
              Service: 'ec2.amazonaws.com'
            Action: 'sts:AssumeRole'
      Policies:
        - PolicyName: SecretsManagerAccessPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: 'Allow'
                Action:
                  - secretsmanager:GetSecretValue
                Resource: "arn:aws:secretsmanager:ap-northeast-1:891377262627:secret:MyRDSPassword"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
      Tags:
        - Key: Name
          Value: S3FullAccessRole

  InstanceProfile:
    Type: 'AWS::IAM::InstanceProfile'
    Properties:
      Roles:
        - Ref: S3FullAccessRole
Outputs:
  EC2SecurityGroupTarget:
    Value: !Ref EC2SecurityGroupTarget
    Export:
      Name: !Sub ${NameBase}-ec2-sg

  MyEC2Instance:
    Value: !Ref MyEC2Instance
    Export:
      Name: !Sub ${NameBase}-ec2
  
  ELBSecurityGroup:
    Value: !Ref ELBSecurityGroup
    Export:
      Name: !Sub "${NameBase}-elb-sg"

  InstancePublicIp:
    Description: "Public IP of the EC2 instance"
    Value: !GetAtt MyEC2Instance.PublicIp



