---
plugin: amazon.aws.aws_ec2
regions:
  - ap-northeast-1
filters:
  instance-state-name: running
  "tag:Name": ec2-target-dynamic-ip
hostnames:
  - ip-address
compose:
  ansible_ssh_private_key_file: /home/taemimizukura/.ssh/raisetech_key.pem
